name: C/C++ CI Lab 4

on:
  push:
    branches: [ "lab4" ]
  pull_request:
    branches: [ "lab4" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./lab4

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: make
    - name: Run tests to verify correct output
      run: |
        # run tests to verify fibonacci output and golden ratio
        OUTPUT=$(./fibonacci)
        echo "$OUTPUT"
        echo "$OUTPUT" | grep -qw "55"
        echo "$OUTPUT" | grep -q "1.618034"

